services:
  ikgw:
    build:
      context: .
    networks:
      - ikgw-network
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure

networks:
  ikgw-network: